// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _test_hls_server_HH_
#define _test_hls_server_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Block_proc24.h"

namespace ap_rtl {

struct test_hls_server : public sc_module {
    // Port declarations 8
    sc_in< sc_lv<577> > input_V_dout;
    sc_in< sc_logic > input_V_empty_n;
    sc_out< sc_logic > input_V_read;
    sc_out< sc_lv<577> > output_V_din;
    sc_in< sc_logic > output_V_full_n;
    sc_out< sc_logic > output_V_write;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;


    // Module declarations
    test_hls_server(sc_module_name name);
    SC_HAS_PROCESS(test_hls_server);

    ~test_hls_server();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    Block_proc24* Block_proc24_U0;
    sc_signal< sc_logic > Block_proc24_U0_ap_start;
    sc_signal< sc_logic > Block_proc24_U0_ap_done;
    sc_signal< sc_logic > Block_proc24_U0_ap_continue;
    sc_signal< sc_logic > Block_proc24_U0_ap_idle;
    sc_signal< sc_logic > Block_proc24_U0_ap_ready;
    sc_signal< sc_logic > Block_proc24_U0_input_V_read;
    sc_signal< sc_lv<577> > Block_proc24_U0_output_V_din;
    sc_signal< sc_logic > Block_proc24_U0_output_V_write;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > Block_proc24_U0_start_full_n;
    sc_signal< sc_logic > Block_proc24_U0_start_write;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<577> ap_const_lv577_lc_1;
    static const sc_logic ap_const_logic_1;
    // Thread declarations
    void thread_Block_proc24_U0_ap_continue();
    void thread_Block_proc24_U0_ap_start();
    void thread_Block_proc24_U0_start_full_n();
    void thread_Block_proc24_U0_start_write();
    void thread_ap_sync_continue();
    void thread_input_V_read();
    void thread_output_V_din();
    void thread_output_V_write();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
